################################################################################
#
# wpebackend-mesa
#
################################################################################

WPEBACKEND_MESA_VERSION = ce2a0ad98d1746d5b0fa743121a6ebb148ab92c1
WPEBACKEND_MESA_SITE = $(call github,WebPlatformForEmbedded,WPEBackend-mesa,$(WPEBACKEND_MESA_VERSION))
WPEBACKEND_MESA_LICENSE = BSD-2-Clause
WPEBACKEND_MESA_LICENSE_FILES = COPYING
WPEBACKEND_MESA_DEPENDENCIES = libxkbcommon mesa3d wayland wpebackend

ifeq ($(BR2_PACKAGE_WPEBACKEND_MESA_GBM),y)
WPEBACKEND_MESA_CONF_OPTS += -DWPE_MESA_GBM=ON
else
WPEBACKEND_MESA_CONF_OPTS += -DWPE_MESA_GBM=OFF
endif

ifeq ($(BR2_PACKAGE_WPEBACKEND_MESA_GBM_EXPORTABLE_DMABUF),y)
WPEBACKEND_MESA_CONF_OPTS += -DWPE_MESA_EXPORTABLE_DMA_BUF=ON
else
WPEBACKEND_MESA_CONF_OPTS += -DWPE_MESA_EXPORTABLE_DMA_BUF=OFF
endif

ifeq ($(BR2_PACKAGE_WPEBACKEND_MESA_WAYLAND_EGL),y)
WPEBACKEND_MESA_CONF_OPTS += -DWPE_MESA_EXPERIMENTAL_WAYLAND_EGL=ON
else
WPEBACKEND_MESA_CONF_OPTS += -DWPE_MESA_EXPERIMENTAL_WAYLAND_EGL=OFF
endif

ifeq ($(BR2_PACKAGE_WPEBACKEND_MESA_TEGRA_QUIRKS),y)
WPEBACKEND_MESA_CONF_OPTS += -DWPE_MESA_DRM_TEGRA_SUPPORT=ON
else
WPEBACKEND_MESA_CONF_OPTS += -DWPE_MESA_DRM_TEGRA_SUPPORT=OFF
endif

$(eval $(cmake-package))
